feat: New error: Failed to pull container from registry.access.redhat.com because of unauthorized
collected-data/jhutar-tenant/1/pod-jhutar-app-yrtti-comp-0-on-push-txrvk-build-source-image-pod-step-build.log

2025-08-19 03:45:10,364:source-build:DEBUG:workspace directory /var/workdir
2025-08-19 03:45:10,364:source-build:DEBUG:working directory /var/workdir/source-build
2025-08-19 03:45:10,368:build-source.source-archive:DEBUG:Stashing any changes to working repo ['git', 'stash']
Saved working directory and index state WIP on (no branch): 6acc311 e2e test commit message
2025-08-19 03:45:10,379:build-source.source-archive:DEBUG:Collecting timestamp of the commit at HEAD ['git', 'show', '-s', '--format=%cI']
2025-08-19 03:45:10,382:build-source.source-archive:DEBUG:Generate source repo file list ['git', 'ls-files', '--recurse-submodules', '-z']
2025-08-19 03:45:10,384:build-source.source-archive:DEBUG:Generate source archive ['tar', 'caf', '/var/workdir/source-build/source_archive/nodejs-devfile-sample-undef-jhutar-6acc311bc5cdcfabeb7a196e39ee456edae88623.tar.gz', '--mtime', '2025-08-19T05:41:27+02:00', '--transform', 's,^,nodejs-devfile-sample-undef-jhutar-6acc311bc5cdcfabeb7a196e39ee456edae88623/,', '--null', '-T-']
2025-08-19 03:45:10,390:build-source.source-archive:DEBUG:Popping any stashed changes to working repo ['git', 'stash', 'pop']
HEAD detached at 6acc311
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (560f01376ee69000592473de33db201c70e14011)
2025-08-19 03:45:10,397:build-source.source-archive:INFO:add source archive directory to sources for bsi: /var/workdir/source-build/source_archive
2025-08-19 03:45:10,550:source-build:ERROR:command execution failure, status: 1, stderr: time="2025-08-19T03:45:10Z" level=fatal msg="Error parsing image name \"docker://registry.access.redhat.com/ubi10/nodejs-22-minimal@sha256:9bb64834bf2c1c846bdf13ad90b2c796974623b78093cbe538803fe5b958622b\": unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication"
Traceback (most recent call last):
  File "/opt/source_build/source_build.py", line 1137, in main
    build_result = build(build_args)
                   ^^^^^^^^^^^^^^^^^
  File "/opt/source_build/source_build.py", line 1101, in build
    source_image = resolve_source_image(base_image, args.registry_allowlist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/source_build/source_build.py", line 504, in resolve_source_image
    return resolve_source_image_by_version_release(binary_image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/source_build/source_build.py", line 465, in resolve_source_image_by_version_release
    image_config = fetch_image_config(f"{name}@{digest}")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/source_build/source_build.py", line 189, in fetch_image_config
    return run(cmd, check=True, text=True, capture_output=True).stdout.strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['skopeo', 'inspect', '--config', '--retry-times', '5', 'docker://registry.access.redhat.com/ubi10/nodejs-22-minimal@sha256:9bb64834bf2c1c846bdf13ad90b2c796974623b78093cbe538803fe5b958622b']' returned non-zero exit status 1.
2025-08-19 03:45:10,551:source-build:INFO:build result {"status": "failure", "message": "Command '['skopeo', 'inspect', '--config', '--retry-times', '5', 'docker://registry.access.redhat.com/ubi10/nodejs-22-minimal@sha256:9bb64834bf2c1c846bdf13ad90b2c796974623b78093cbe538803fe5b958622b']' returned non-zero exit status 1."}
2025-08-19 03:45:10,551:source-build:INFO:write build result into file /tekton/results/BUILD_RESULT