feat: Update all GH actions used except codeql-action/upload-sarif
Updating codeql-action/upload-sarif caused this and would require more work:

[...]
Error details: instance.runs[0].results[37].fixes[0].artifactChanges is not of a type(s) array
  {
    "path": [
      "runs",
      0,
      "results",
      37,
      "fixes",
      0,
      "artifactChanges"
    ],
    "property": "instance.runs[0].results[37].fixes[0].artifactChanges",
    "message": "is not of a type(s) array",
    "schema": {
      "description": "One or more artifact changes that comprise a fix for a result.",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/artifactChange"
      }
    },
    "instance": null,
    "name": "type",
    "argument": [
      "array"
    ],
    "stack": "instance.runs[0].results[37].fixes[0].artifactChanges is not of a type(s) array"
  }
Error: Unable to upload "results.sarif" as it is not valid SARIF:
- instance.runs[0].results[23].fixes[0].artifactChanges is not of a type(s) array
[...]