feat: New error: DNF failed to install package because GPG check failed
When working on KONFLUX-10176

run-2025-09-22T11_18_30_168225/openstack-tenant/1/pod-edpm-hardened-u85159135a27023f5a9263b65a70d4dc95ebc408ec7e3-pod-step-build.log

[2025-09-11T08:23:21,900695702+00:00] Run buildah build
[2025-09-11T08:23:21,901637952+00:00] ip link set lo up && buildah build --volume /tmp/cachi2:/cachi2 --volume /var/workdir/fetched.repos.d:/etc/yum.repos.d --pull=never --build-arg=batch=18.0_20250605.1 --build-arg=tags=18.0\ 18.0_20250605.1 --build-arg=version=18.0.9 --security-opt=unmask=/proc/interrupts --label architecture=x86_64 --label vcs-type=git --label vcs-ref=0d5e68c7a0d4af533d7346cf9e16d5f2fe1cc49b --label quay.expires-after=5d --label build-date=2025-09-11T08:23:21Z --tls-verify=true --no-cache --ulimit nofile=4096:4096 --http-proxy=false -f /tmp/Containerfile.ZEFSIT -t quay.io/redhat-user-workloads/openstack-tenant/openstack-18-0/edpm-hardened-uefi:on-pr-0d5e68c7a0d4af533d7346cf9e16d5f2fe1cc49b .
[1/2] STEP 1/7: FROM registry.redhat.io/rhel9-4-els/rhel:9.4@sha256:00e433b9ad6b154ec6e68fc8afb76e4d4771b17bc806074ceb74ef0ba0e380de AS builder
[1/2] STEP 2/7: RUN . /cachi2/cachi2.env &&     dnf -y install rhoso-images-edpm-x86_64 tar
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Repository 'rhoso-18.0-for-rhel-9-x86_64-rpms' is missing name in configuration, using id.
Repository 'rhel-9-for-x86_64-appstream-e4s-rpms__9_DOT_4' is missing name in configuration, using id.
Repository 'rhel-9-for-x86_64-baseos-e4s-rpms__9_DOT_4' is missing name in configuration, using id.
rhoso-18.0-for-rhel-9-x86_64-rpms               2.0 MB/s | 2.1 kB     00:00
rhel-9-for-x86_64-appstream-e4s-rpms__9_DOT_4   3.8 MB/s | 3.9 kB     00:00
rhel-9-for-x86_64-baseos-e4s-rpms__9_DOT_4      203 MB/s | 248 kB     00:00
Package tar-2:1.34-6.el9_4.1.x86_64 is already installed.
Dependencies resolved.
===================================================================================================
 Package                    Arch    Version                Repository                          Size
===================================================================================================
Installing:
 rhoso-images-edpm-x86_64   noarch  18.0-20250903.2.el9ost rhoso-18.0-for-rhel-9-x86_64-rpms  1.3 G
Installing dependencies:
 rhoso-images-base          noarch  18.0-20250903.2.el9ost rhoso-18.0-for-rhel-9-x86_64-rpms  7.5 k
 rhoso-images-metadata      noarch  18.0-20250903.2.el9ost rhoso-18.0-for-rhel-9-x86_64-rpms  7.7 k
 rhoso-release              noarch  18.0.12-1.el9ost       rhoso-18.0-for-rhel-9-x86_64-rpms  6.9 k

Transaction Summary
===================================================================================================
Install  4 Packages

Total size: 1.3 G
Installed size: 1.4 G
Downloading Packages:
Package rhoso-images-base-18.0-20250903.2.el9ost.noarch.rpm is not signed
Package rhoso-images-edpm-x86_64-18.0-20250903.2.el9ost.noarch.rpm is not signed
Package rhoso-images-metadata-18.0-20250903.2.el9ost.noarch.rpm is not signed
Error: GPG check FAILED
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN . /cachi2/cachi2.env &&     dnf -y install rhoso-images-edpm-x86_64 tar": exit status 1