feat: New error: Failed to prefetch dependencies due to invalid input when fetching tags
When working on KONFLUX-10175

service-mesh-tenant/1/pod-ossm-3-2-7672bb71f5dcda4b3bec1413c3d0d13f78ab8161f3c7dfc519-pod-step-prefetch-dependencies.log

INFO: Using mounted CA bundle: /mnt/trusted-ca/ca-bundle.crt
'/mnt/trusted-ca/ca-bundle.crt' -> '/etc/pki/ca-trust/source/anchors/ca-bundle.crt'
Registering with Red Hat subscription manager.
Executing: subscription-manager register --org 11009103 --activationkey rh-ossm-istio-proxy-production-build-els_9_4
The system has been registered with ID: 23df700b-a3a5-449c-acbb-14b8871dfd41
The registered system name is: ossm-3-2-7672bb71f5dcda4b3bec1413c3d0d13f78ab8161f3c7dfc519-pod
Executing: git fetch --tags
2025-09-17 12:50:53,180 ERROR InvalidInput: 1 validation error for user input\npackages\n  Value error, package path does not exist (or is not a directory): rpm-lockfiles/proxy-debug/golang
Error: InvalidInput: 1 validation error for user input
packages
  Value error, package path does not exist (or is not a directory): rpm-lockfiles/proxy-debug/golang
Unregistering from: subscription.rhsm.redhat.com:443/subscription
System has been unregistered.