feat: New error: Failed to prefetch dependencies due to go env error
When working on KONFLUX-10175

service-mesh-tenant/1/pod-ossm-3-2-963456391dabac376d995e320caa806de7b53e2cd673a7fb97-pod-step-prefetch-dependencies.log

INFO: Using mounted CA bundle: /mnt/trusted-ca/ca-bundle.crt
'/mnt/trusted-ca/ca-bundle.crt' -> '/etc/pki/ca-trust/source/anchors/ca-bundle.crt'
Registering with Red Hat subscription manager.
Executing: subscription-manager register --org 11009103 --activationkey rh-ossm-istio-proxy-production-build-els_9_4
The system has been registered with ID: ba58a14c-333e-426c-9d26-ab42928c7248
The registered system name is: ossm-3-2-963456391dabac376d995e320caa806de7b53e2cd673a7fb97-pod
Executing: git fetch --tags
2025-09-17 13:58:03,660 INFO Fetching the gomod dependencies at subpath proxy
2025-09-17 13:58:03,993 ERROR The command "go env GOWORK" failed
2025-09-17 13:58:03,994 ERROR STDERR:
go: downloading go1.24 (linux/amd64)
go: download go1.24 for linux/amd64: toolchain not available
2025-09-17 13:58:10,242 ERROR PackageManagerError: Go execution failed: `go env GOWORK` failed with rc=1
Error: PackageManagerError: Go execution failed: `go env GOWORK` failed with rc=1
  The cause of the failure could be:
  - something is broken in hermeto
  - something is wrong with your repository
  - communication with an external service failed (please try again)
  The output of the failing command should provide more details, please check the logs.
Unregistering from: subscription.rhsm.redhat.com:443/subscription
System has been unregistered.